name: veteranam
description: veteran
version: 1.3.8+113
publish_to: none

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.3
  app_tracking_transparency: ^2.0.6
  basic_dropdown_button: ^1.1.1+1 # this is our own custom package
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.1
  cloud_functions: ^6.0.1
  collection: ^1.19.1
  connectivity_plus: ^6.1.5
  dartz: ^0.10.1
  device_info_plus: ^11.5.0
  dio: ^5.9.0
  easy_debounce: ^2.0.3
  email_validator: ^3.0.0
  equatable: ^2.0.7
  feedback: ^3.2.0
  file_picker: ^10.3.2
  firebase_analytics: ^12.0.1
  firebase_app_check: ^0.4.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_crashlytics: ^5.0.1
  firebase_messaging: ^16.0.1
  firebase_performance: ^0.11.0
  firebase_remote_config: ^6.0.1
  firebase_storage: ^13.0.1
  flutter:
    sdk: flutter
  flutter_app_badger:
    git:
      url: https://github.com/g123k/flutter_app_badger.git
      ref: 33cbee6
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^7.1.2
  flutter_local_notifications: ^19.4.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.4
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.8.0
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0 # Used for dependency injection
  go_router: ^16.2.1 # Decoupled routing  package which is a must for any app
  google_mobile_ads: ^6.0.0
  google_sign_in: ^7.1.1
  image_picker: ^1.2.0
  in_app_review: ^2.0.11
  injectable: ^2.5.1 # Used for dependency injection
  intl: ^0.20.2
  json_serializable: ^6.11.0
  material_symbols_icons: ^4.2867.0
  optimized_search_field: ^2.0.2 # this is our own custom package
  package_info_plus: ^8.3.1
  # path_drawing: ^1.0.1
  # pdf: ^3.11.0
  # printing: ^5.13.1
  path_provider: ^2.1.5
  sentry_flutter: ^9.6.0
  share_plus: ^11.1.0
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  skeletonizer: ^2.1.0
  sliver_center: ^1.1.2 # this is our own custom package
  url_launcher: ^6.3.2
  web: ^1.1.1

  # web: ^1.1.0

dependency_overrides:
  flutter_secure_storage_web: ^2.0.0-beta.1

#   vector_graphics_compiler:
#     git:
#       url: https://github.com/nohli/vector_graphics
#       path: packages/vector_graphics_compiler
#       ref: js_interop

dev_dependencies:
  bloc_test: ^10.0.0

  build_runner: ^2.7.1 # Used for class generation
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.8.1 # Used for dependency injection for get_it
  integration_test:
    sdk: flutter
  intl_utils: ^2.8.11
  json_annotation: ^4.9.0 # Defines the annotations used by json_serializable
  mockito: ^5.5.0 # Used for mocking classes
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  sentry_dart_plugin: ^3.1.1
  url_launcher_platform_interface: ^2.3.2
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true

  # icons
  assets:
    - assets/images/
    - assets/markdown/

  fonts:
    - family: Veteranam
      fonts:
        - asset: assets/fonts/veteranam_icons.woff
          weight: 400
          style: normal

    - family: Gilroy
      fonts:
        # - asset: assets/fonts/Gilroy-Thin.woff
        #   weight: 100
        #   style: normal
        # - asset: assets/fonts/Gilroy-Light.woff
        #   weight: 300
        #   style: normal
        - asset: assets/fonts/Gilroy-Medium.woff
          weight: 400
          style: normal
        - asset: assets/fonts/Gilroy-Regular.woff
          weight: 500
          style: normal
        # - asset: assets/fonts/Gilroy-Semibold.woff
        #   weight: 600
        #   style: normal
        - asset: assets/fonts/Gilroy-Bold.woff
          weight: 700
        #   style: normal
        # - asset: assets/fonts/Gilroy-Extrabold.woff
        #   weight: 800
        #   style: normal
        # - asset: assets/fonts/Gilroy-Black.woff
        #   weight: 900
        #   style: normal

        # - asset: assets/fonts/Gilroy-ThinItalic.woff
        #   weight: 100
        #   style: italic
        # - asset: assets/fonts/Gilroy-LightItalic.woff
        #   weight: 300
        #   style: italic
        # - asset: assets/fonts/Gilroy-MediumItalic.woff
        #   weight: 400
        #   style: italic
        # - asset: assets/fonts/Gilroy-RegularItalic.woff
        #   weight: 500
        #   style: italic
        # - asset: assets/fonts/Gilroy-SemiboldItalic.woff
        #   weight: 600
        #   style: italic
        # - asset: assets/fonts/Gilroy-BoldItalic.woff
        #   weight: 700
        #   style: italic
        # - asset: assets/fonts/Gilroy-ExtraboldItalic.woff
        #   weight: 800
        #   style: italic
        # - asset: assets/fonts/Gilroy-HeavyItalic.woff
        #   weight: 900
        #   style: italic

sentry:
  # enabled by default
  #upload_debug_symbols: true
  # disabled by default
  upload_sources: true
  # disabled by default
  upload_source_maps: true
  project: veteran
  org: coding-house-studio-llc

  # set by env. var. SENTRY_AUTH_TOKEN
  # We need this variable only when push release build. Used only when upload_source_maps
  auth_token:

  # disabled by default
  # wait_for_processing: true

  ignore_missing: true

  # default 'warning'
  log_level: error

  # default to build/web
  #web_build_path: ...

  # default to name@version from pubspec
  #release: ...
# flutter_intl:
#   enabled: true # Required. Must be set to true to activate the package. Default: false
#   class_name: AppLocalizations # Optional. Sets the name for the generated localization class. Default: S
#   main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
#   arb_dir: lib/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
#   output_dir: lib/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
#   use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
#   localizely: # Optional settings if you use Localizely platform. Read more: https://localizely.com/blog/flutter-localization-step-by-step/?tab=automated-using-flutter-intl
#     project_id: # Get it from the https://app.localizely.com/projects page.
#     branch: # Get it from the “Branches” page on the Localizely platform, in case branching is enabled and you want to use a non-main branch.
#     upload_overwrite: # Set to true if you want to overwrite translations with upload. Default: false
#     upload_as_reviewed: # Set to true if you want to mark uploaded translations as reviewed. Default: false
#     upload_tag_added: # Optional list of tags to add to new translations with upload (e.g. ['new', 'New translation']). Default: []
#     upload_tag_updated: # Optional list of tags to add to updated translations with upload (e.g. ['updated', 'Updated translation']). Default: []
#     upload_tag_removed: # Optional list of tags to add to removed translations with upload (e.g. ['removed', 'Removed translation']). Default: []
#     download_empty_as: # Set to empty|main|skip, to configure how empty translations should be exported from the Localizely platform. Default: empty
#     download_include_tags: # Optional list of tags to be downloaded (e.g. ['include', 'Include key']). If not set, all string keys will be considered for download. Default: []
#     download_exclude_tags: # Optional list of tags to be excluded from download (e.g. ['exclude', 'Exclude key']). If not set, all string keys will be considered for download. Default: []
#     ota_enabled: # Set to true if you want to use Localizely Over-the-air functionality. Default: false
